train folder: 'trainset'
output folder: 'output'


train split: 0.8
learning rate: 0.0001
train epochs: 50
batch size: 5
Dropout: 0.25


bidirectional: False
hidden sizes: [100, 100, 100]
embedding size: 100

# use the debug size for only loading 20 files instead of the
# whole dataset. (comment out if using the whole dataset)
debug size: 20